<a href="https://colab.research.google.com/github/gaur8av/python_numpy/blob/main/Numpy7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Indexing in numpy

In [ ]:
import numpy as np
var=np.array([1,5,6,7,3])
print(var[3])
var1=np.array([[1,2,4],[6,7,8]])
print(var1)
print()
print(var1[0,2])
print()
var2=np.array([[[1,2,4],[6,7,8]],[[2,9,0],[6,1,8]]])
print(var2)
print()
print(var2[1,1,2])

Slicing in numpy suppose
x[start:stop:step]=it gives or return list



In [15]:
var3=np.array([1,5,6,7,3,8,9,0])
print(var3[1:5])
print()
print(var3[0:])
print()
print(var3[::-1])

[5 6 7 3]

[1 5 6 7 3 8 9 0]

[0 9 8 3 7 6 5 1]


slicing in 2d array and 3d array


In [19]:
var4=np.array([[1,3,5,7],[5,6,9,3]])
print(var4[0,0:])
print()
print(var4[1,2:5])
print()
print(var4[1,3:5])

[1 3 5 7]

[9 3]

[3]


In [21]:
x=np.array([[[-1,5,2,3],[4,-7,6,0]],[[5,8,1,1],[0,6,3,2]]])
print(x)
print()
print(x[0,0,0:])
print()
print(x[1,0,2:5])
print()
print(x[0,1,3:5])


[[[-1  5  2  3]
  [ 4 -7  6  0]]

 [[ 5  8  1  1]
  [ 0  6  3  2]]]

[-1  5  2  3]

[1 1]

[0]
