<a href="https://colab.research.google.com/github/gaur8av/python_numpy/blob/main/Numpy8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Iteration in numpy array

In [2]:
import numpy as np
x=np.array([1,2,8,5,-2,-3,0])
print(x)
print()
for i in x:
  print(i,end=" ")

[ 1  2  8  5 -2 -3  0]

1 2 8 5 -2 -3 0 

In [ ]:
y=np.array([[1,2,8],[5,-2,-3]])
print(y)
print()
for j in y:
  print(j)

print()

for k in y:
  for p in k:
    print(p)


by using nditer() function

In [13]:
z=np.array([[[1,2,8],[5,-2,-3]],[[2,3,4],[10,20,0]]])
print(z)
print()
for i in np.nditer(z):
  print(i,end=" ")

print()
for j,index in np.ndenumerate(z):
  print(j,index)

[[[ 1  2  8]
  [ 5 -2 -3]]

 [[ 2  3  4]
  [10 20  0]]]

1 2 8 5 -2 -3 2 3 4 10 20 0 
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 8
(0, 1, 0) 5
(0, 1, 1) -2
(0, 1, 2) -3
(1, 0, 0) 2
(1, 0, 1) 3
(1, 0, 2) 4
(1, 1, 0) 10
(1, 1, 1) 20
(1, 1, 2) 0
