<a href="https://colab.research.google.com/github/gaur8av/python_numpy/blob/main/Numpy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Arithmetic function in Numpy

In [2]:
import numpy as np
var=np.array([1,3,-8,7,0,15,-20])
print("min: ",np.min(var))
print("max: ",np.max(var))

min:  -20
max:  15


In [5]:
var=np.array([1,3,-8,7,0,15,-20])
print("min no. and index: ",np.min(var),np.argmin(var))
print("max no. and index: ",np.max(var),np.argmax(var))

min no. and index:  -20 6
max no. and index:  15 5


in multidirection array ther is concept of axis for finding min and max n

o axis=0 (column) axis=1 (row)

In [12]:
var1=np.array([[1,3,5],[2,7,-5],[0,-3,15]])
print("min: ",np.min(var1,axis=1))
print("max: ",np.max(var1,axis=1))
print()
print("min: ",np.min(var1,axis=0))
print("max: ",np.max(var1,axis=0))


min:  [ 1 -5 -3]
max:  [ 5  7 15]

min:  [ 0 -3 -5]
max:  [ 2  7 15]


In [23]:
var2=np.array([[1,3,5],[2,7,8],[0,3,15]])
print(var2)
print()
print("sum is:" ,np.sum(var2,axis=0))    #along column
print("sum is:" ,np.sum(var2,axis=1))    #along row

[[ 1  3  5]
 [ 2  7  8]
 [ 0  3 15]]

sum is: [ 3 13 28]
sum is: [ 9 17 18]


In [24]:
var2=np.array([[1,3,5],[2,7,5],[0,6,15]])
print(var2)
print()
p=np.sqrt(var2)
print(p)

[[ 1  3  5]
 [ 2  7  5]
 [ 0  6 15]]

[[1.         1.73205081 2.23606798]
 [1.41421356 2.64575131 2.23606798]
 [0.         2.44948974 3.87298335]]


In [4]:
import numpy as np
var2=np.array([[1,3,5],[2,7,5],[0,6,15]])
print(var2)
print()
p=np.sin(var2)
q=np.cos(var2)
print(p)
print()
print(q)

[[ 1  3  5]
 [ 2  7  5]
 [ 0  6 15]]

[[ 0.84147098  0.14112001 -0.95892427]
 [ 0.90929743  0.6569866  -0.95892427]
 [ 0.         -0.2794155   0.65028784]]

[[ 0.54030231 -0.9899925   0.28366219]
 [-0.41614684  0.75390225  0.28366219]
 [ 1.          0.96017029 -0.75968791]]
