<a href="https://colab.research.google.com/github/gaur8av/python_numpy/blob/main/Numpu11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy array Functions

In [ ]:
#serch function

import numpy as np
x=np.array([1,3,5,0,7,51,5,5,32,46,67])

y=np.where(x==5)
print(y)
print()
z=np.where(x%2==0)
print(z)
print()
for i in x:
  if(i==5):
    print(i,end=" ")


Shuffle function

In [8]:
import numpy as np
var=np.array([1,2,3,4,5])
print(var)
print()
np.random.shuffle(var)
print(var)

[1 2 3 4 5]

[5 2 1 4 3]


unique function

In [12]:
var_1=np.array([1,2,3,4,5,11,12,22,5,6,10,2,12,6,4])
print(var_1)
print()
x = np.unique(var_1,return_index=True,return_counts=True)
print(x)

[ 1  2  3  4  5 11 12 22  5  6 10  2 12  6  4]

(array([ 1,  2,  3,  4,  5,  6, 10, 11, 12, 22]), array([ 0,  1,  2,  3,  4,  9, 10,  5,  6,  7]), array([1, 2, 1, 2, 2, 2, 1, 1, 2, 1]))


Resize function

In [15]:
var2=np.array([1,2,3,4,5,6])
print(var2)
print()
y=np.resize(var2,(2,3))
print(y)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


Flatten (2D array convert into 1D by order) and Ravel function

In [24]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)

print()
print("Flatten array: ", y.flatten(order='F'))
print()
print("Ravel array :", np.ravel(y))


[[1 2]
 [3 4]
 [5 6]]

Flatten array:  [1 3 5 2 4 6]

Ravel array : [1 2 3 4 5 6]
