<a href="https://colab.research.google.com/github/gaur8av/python_numpy/blob/main/Numpy10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Join and Split functions

In [ ]:
# Join( using Concatenate function)
import numpy as np
x = np.array([1,4,5,9])
y = np.array([2,9,3,4])

z = np.concatenate((x,y))
print(z)

[1 4 5 9 2 9 3 4]


In [ ]:
var_1=np.array([[1,3,0,-2],[-4,0,-5,9]])
var_2=np.array([[0,6,3,-8],[1,4,-6,3]])

var_3=np.concatenate((var_1,var_2),axis=1)
print(var_3)
print()
var_4=np.concatenate((var_1,var_2),axis=0)
print(var_4)

[[ 1  3  0 -2  0  6  3 -8]
 [-4  0 -5  9  1  4 -6  3]]

[[ 1  3  0 -2]
 [-4  0 -5  9]
 [ 0  6  3 -8]
 [ 1  4 -6  3]]


In [ ]:
#using stack function
var_1 = np.array([[1,15,10,-2],[-4,0,-52,9]])
var_2 = np.array([[0,66,30,-8],[1,46,-6,31]])
print(var_1)
print()
print(var_2)
print()

var_new = np.stack((var_1,var_2),axis=0)
print(var_new)
print()
var_new1 = np.stack((var_1,var_2),axis=1)
print(var_new1)
print()
var_new2 = np.hstack((var_1,var_2))
print(var_new2)
print()
var_new3 = np.vstack((var_1,var_2))
print(var_new3)

[[  1  15  10  -2]
 [ -4   0 -52   9]]

[[ 0 66 30 -8]
 [ 1 46 -6 31]]

[[[  1  15  10  -2]
  [ -4   0 -52   9]]

 [[  0  66  30  -8]
  [  1  46  -6  31]]]

[[[  1  15  10  -2]
  [  0  66  30  -8]]

 [[ -4   0 -52   9]
  [  1  46  -6  31]]]

[[  1  15  10  -2   0  66  30  -8]
 [ -4   0 -52   9   1  46  -6  31]]

[[  1  15  10  -2]
 [ -4   0 -52   9]
 [  0  66  30  -8]
 [  1  46  -6  31]]


In [ ]:
#split function
x = np.array([1,6,0,4,5,9])
print(x)
print()
ar = np.array_split(x,3)
print()
print(ar)
print(type(ar))
print(ar[0])


[1 6 0 4 5 9]


[array([1, 6]), array([0, 4]), array([5, 9])]
<class 'list'>
[1 6]


In [ ]:
p = np.array([[1,3,5,7,9],[0,2,4,6,8]])
print(p)
print()
q = np.array_split(p,5)
print(q)
print(type(q))
print(q[0])

[[1 3 5 7 9]
 [0 2 4 6 8]]

[array([[1, 3, 5, 7, 9]]), array([[0, 2, 4, 6, 8]]), array([], shape=(0, 5), dtype=int64), array([], shape=(0, 5), dtype=int64), array([], shape=(0, 5), dtype=int64)]
<class 'list'>
[[1 3 5 7 9]]
