<a href="https://colab.research.google.com/github/gaur8av/python_numpy/blob/main/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Arithmetic operations in Numpy Arrays

In [2]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
y=x+3
print()
print(y)

[1 2 3 4]

[4 5 6 7]


In [22]:

import numpy as np
x1=np.array([1,32,23,14])
y2=x1*5
#y3=x1/5
y4=x1%5
print(np.divide(x1,5))
print()
print(y2,sep=" ")
print()
var1=np.array([1,3,-5,-7])   #divide(var1,var2)=var1/var2
var2=np.array([1,-2,4,-6])

print(np.add(var1,var2),np.divide(var1,var2),np.subtract(var1,var2),np.multiply(var1,var2),np.mod(var1,var2),sep=" ")






[0.2 6.4 4.6 2.8]

[  5 160 115  70]

[  2   1  -1 -13] [ 1.         -1.5        -1.25        1.16666667] [ 0  5 -9 -1] [  1  -6 -20  42] [ 0 -1  3 -1]


In [24]:
var_1=np.array([[1,2,-4,7],[3,2,0,-8],[0,1,3,5]])
var_2=np.array([[1,-2,-4,0],[9,7,0,-8],[0,1,3,8]])
print(np.add(var_1,var_2))
print()
print(np.subtract(var_1,var_2))
print()
print(np.multiply(var_1,var_2))
print()
print(np.divide(var_1,var_2))
print()
print(np.mod(var_1,var_2))
print()
print(np.reciprocal(var_1))



[[  2   0  -8   7]
 [ 12   9   0 -16]
 [  0   2   6  13]]

[[ 0  4  0  7]
 [-6 -5  0  0]
 [ 0  0  0 -3]]

[[ 1 -4 16  0]
 [27 14  0 64]
 [ 0  1  9 40]]

[[ 1.         -1.          1.                 inf]
 [ 0.33333333  0.28571429         nan  1.        ]
 [        nan  1.          1.          0.625     ]]

[[0 0 0 0]
 [3 2 0 0]
 [0 0 0 5]]

[[                   1                    0                    0
                     0]
 [                   0                    0 -9223372036854775808
                     0]
 [-9223372036854775808                    1                    0
                     0]]


<ipython-input-24-e758ad155079>:9: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(var_1,var_2))
<ipython-input-24-e758ad155079>:9: RuntimeWarning: invalid value encountered in divide
  print(np.divide(var_1,var_2))
<ipython-input-24-e758ad155079>:11: RuntimeWarning: divide by zero encountered in remainder
  print(np.mod(var_1,var_2))
<ipython-input-24-e758ad155079>:13: RuntimeWarning: divide by zero encountered in reciprocal
  print(np.reciprocal(var_1))
<ipython-input-24-e758ad155079>:13: RuntimeWarning: invalid value encountered in reciprocal
  print(np.reciprocal(var_1))
