<a href="https://colab.research.google.com/github/gaur8av/python_numpy/blob/main/Numpy6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Shape and Reshape in Numpy

In [ ]:
import numpy as np
x=np.array([[1,2],[4,5]])
print(x)
print()
print(x.shape)
print()
y=np.array([1,2,3,4],ndmin=4)
print(y)
print(y.shape)

Reshape using reshape(a,b) function a=no of row , b=no of column

In [24]:
x=np.array([1,2,3,4,5,65,7,8,9])
print(x)
print()
var=x.reshape(3,3)
print(var,var.shape, sep=" ")

[ 1  2  3  4  5 65  7  8  9]

[[ 1  2  3]
 [ 4  5 65]
 [ 7  8  9]] (3, 3)


In [30]:
var2=np.array([1,2,3,4,5,65,7,8,9,10,11,12])
print(x)
print()
var3=var2.reshape(2,2,3)
print()
print(var3.shape)
print()
print(var3,var3.ndim,sep="  ")
one=var3.reshape(-1)                   #convert into 1-D array
print()
print(one)

[ 1  2  3  4  5 65  7  8  9]


(2, 2, 3)

[[[ 1  2  3]
  [ 4  5 65]]

 [[ 7  8  9]
  [10 11 12]]]  3

[ 1  2  3  4  5 65  7  8  9 10 11 12]
