<a href="https://colab.research.google.com/github/gaur8av/python_numpy/blob/main/Numpy7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Broadcasting in numpy


In [ ]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([1,2,3])
#print(np.add(x,y))   #gives broadcasting error


In [ ]:
y=np.array([1,2,3])
print(y.shape)
print()
z=np.array([[1],[2],[3]])
print(z)
print()
print(z.shape)
print()
print(y+z)



In [9]:
var1=np.array([[3],[8]])
print(var1)
print(var1.shape)
print()
var2=np.array([[1,2,3],[4,5,6]])
print(var2)
print(var1.shape)
print()
print(var1+var2)

[[3]
 [8]]
(2, 1)

[[1 2 3]
 [4 5 6]]
(2, 1)

[[ 4  5  6]
 [12 13 14]]
