<a href="https://colab.research.google.com/github/gaur8av/python_numpy/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Create numpy array using numpy function

zeros

In [ ]:
import numpy as np
ar_zero=np.zeros(4)
print(ar_zero)
print()
ar_zero1=np.zeros((3,4))
print(ar_zero1)



array element with '1's

In [ ]:
import numpy as np
ar_one=np.ones(5)
print(ar_one)
print(type(ar_one))
print()
ar_one1=np.ones((4,5,6))
print(ar_one1)

Empty array

In [9]:
ar_emp=np.empty(4)
print(ar_emp)

[0. 0. 0. 0.]


Range array using arange function

In [ ]:
ar_ran=np.arange(2)
print(ar_ran)

Diagonal

In [16]:
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


Array element with special interval using linespace function

In [19]:
ar_lin=np.linspace(1,10,num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]
