<a href="https://colab.research.google.com/github/gaur8av/python_numpy/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data type in numpy array

In [2]:
import numpy as np
var=np.array([1,2,3,4])
print("data type: ",var.dtype)

data type:  int64


In [3]:
var=np.array([1.0,2.5,3.65,4.2,5.09])
print("data type: ",var.dtype)

data type:  float64


In [9]:
var=np.array(['G','a','u','r','a','v','1','@','54'])
print("data type: ",var.dtype)

data type:  <U2


convert one data type to another using data type as a function

In [14]:
x=np.array([1,2,3,4])
print("data type :",x.dtype)
print()
y = np.array([1,2,3,4],dtype=np.float128)
print("data type: ",y.dtype)
print(y)
print()
x1=np.array([1,2,3,4],dtype="f")
print("data type :",x1.dtype)
print(x1)

data type : int64

data type:  float128
[1. 2. 3. 4.]

data type : float32
[1. 2. 3. 4.]


In [ ]:
x2=np.array([1,2,3,4])
print("data type :",x.dtype)
print()
new=np.float64(x2)   #covert into float
print("data type: ",new.dtype)
print(new)
print()
x3=np.array([1,-2,3,0])
print("data type :",x3.dtype)
print()
new1=np.bool8(x3)
print("data type: ",new1.dtype)
print(x3)


convert direct using astype function

In [19]:
x=np.array([1,2,3,4])
new_1=x.astype(complex)
print(x)

print(new_1)

[1 2 3 4]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
